# Generated by Django 5.1.7 on 2025-05-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='re_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn', models.CharField(max_length=25)),
                ('ds', models.TextField()),
                ('ig', models.CharField(max_length=25)),
                ('ins', models.TextField()),
            ],
        ),
    ]
